"""User Model updated with validation

Revision ID: 0d75adc53332
Revises: 38ee8ccb97eb
Create Date: 2023-08-02 15:01:02.340274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d75adc53332'
down_revision = '38ee8ccb97eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
