"""One to Many relationship Restaurant Order

Revision ID: 10f74bfeefb1
Revises: 6d878e9df15c
Create Date: 2023-08-07 11:18:55.410651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f74bfeefb1'
down_revision = '6d878e9df15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurant_id_orders', 'restaurants', ['restaurant_id'], ['restaurant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurant_id_orders', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
