"""One to Many relationship MenuItem OrderItem

Revision ID: 25fe15e7f31a
Revises: fcc0efbb605c
Create Date: 2023-08-07 11:57:41.241482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fe15e7f31a'
down_revision = 'fcc0efbb605c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_id_orderitems', 'menuitems', ['item_id'], ['item_id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_id_orders', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_item_id_orders', 'menuitems', ['item_id'], ['item_id'])

    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_id_orderitems', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
