"""Restaurant promotion 1-many relationship with more attributes added to promotion

Revision ID: 2a05bdd06b21
Revises: 7b4212d6fd89
Create Date: 2023-08-05 19:13:26.904304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a05bdd06b21'
down_revision = '7b4212d6fd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyaltyprograms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurant_id_loyaltyprograms', 'restaurants', ['restaurant_id'], ['restaurant_id'])

    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurants_id_menu_item', 'restaurants', ['restaurant_id'], ['restaurant_id'])

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['restaurant_id'])
        batch_op.drop_column('discount_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('active')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurants_id_menu_item', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('loyaltyprograms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurant_id_loyaltyprograms', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
