"""LoyaltyProgram Restaurant 1-1 relationship

Revision ID: 2e06b18723b8
Revises: ef6bc0d1c78a
Create Date: 2023-08-03 17:29:19.202203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e06b18723b8'
down_revision = 'ef6bc0d1c78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyaltyprograms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['restaurant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyaltyprograms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
