"""One to Many relationship Order OrderItem

Revision ID: 34d26dc55da4
Revises: acf861a62f11
Create Date: 2023-08-07 11:04:41.944827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d26dc55da4'
down_revision = 'acf861a62f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_id_orderitems', 'orders', ['order_id'], ['order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_id_orderitems', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
