"""One to Many relationship User(customer) Order

Revision ID: 6d878e9df15c
Revises: 34d26dc55da4
Create Date: 2023-08-07 11:11:40.141897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d878e9df15c'
down_revision = '34d26dc55da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_id_orders', 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_orders', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
