"""LoyaltyProgram Restaurant 1-1 relationship

Revision ID: 7b4212d6fd89
Revises: 2e06b18723b8
Create Date: 2023-08-03 17:31:47.525811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4212d6fd89'
down_revision = '2e06b18723b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyaltyprograms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurant_id_loyaltyprograms', 'restaurants', ['restaurant_id'], ['restaurant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyaltyprograms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurant_id_loyaltyprograms', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
