"""Change in menu items

Revision ID: 818611c2de35
Revises: e3890ab799d4
Create Date: 2023-07-30 22:04:22.199581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818611c2de35'
down_revision = 'e3890ab799d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customization_options', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_column('customization_options')

    # ### end Alembic commands ###
