"""Restaurant promotion 1-many relationship with more attributes added to promotion

Revision ID: acf861a62f11
Revises: 2a05bdd06b21
Create Date: 2023-08-05 19:19:56.036788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf861a62f11'
down_revision = '2a05bdd06b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyaltyprograms',
    sa.Column('loyalty_program_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('loyalty_tier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], name='fk_restaurant_id_loyaltyprograms'),
    sa.PrimaryKeyConstraint('loyalty_program_id')
    )
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurants_id_menu_item', 'restaurants', ['restaurant_id'], ['restaurant_id'])

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_restaurant_id_promotions', 'restaurants', ['restaurant_id'], ['restaurant_id'])
        batch_op.drop_column('discount_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('fk_restaurant_id_promotions', type_='foreignkey')
        batch_op.drop_column('active')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurants_id_menu_item', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    op.drop_table('loyaltyprograms')
    # ### end Alembic commands ###
