"""Restaurant StaffMapping one to many rel

Revision ID: b9d87cd0e64c
Revises: baa6d662379a
Create Date: 2023-08-07 22:28:18.627725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d87cd0e64c'
down_revision = 'baa6d662379a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurant_id_mappings', 'restaurants', ['restaurant_id'], ['restaurant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurant_id_mappings', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
