"""Models

Revision ID: e3890ab799d4
Revises: 
Create Date: 2023-07-28 21:02:20.935684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3890ab799d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('admin_email', sa.String(length=120), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_username')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_email'),
    sa.UniqueConstraint('customer_name')
    )
    op.create_table('loyaltyprograms',
    sa.Column('loyalty_program_id', sa.Integer(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('loyalty_tier', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('loyalty_program_id')
    )
    op.create_table('mappings',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('staff_role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('menuitems',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('orderitems',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=100), nullable=False),
    sa.Column('order_total', sa.Float(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('paymenttransactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('promotions',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('promotion_name', sa.String(length=200), nullable=False),
    sa.Column('promotion_description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_table('restaurants',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=200), nullable=False),
    sa.Column('restaurant_email', sa.String(length=120), nullable=False),
    sa.Column('restaurant_password', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('ambience', sa.String(length=100), nullable=False),
    sa.Column('cuisines_offered', sa.String(length=200), nullable=False),
    sa.Column('operating_hours', sa.String(length=200), nullable=False),
    sa.Column('contact_info', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('restaurant_email')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('review_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('restaurants')
    op.drop_table('promotions')
    op.drop_table('paymenttransactions')
    op.drop_table('orders')
    op.drop_table('orderitems')
    op.drop_table('menuitems')
    op.drop_table('mappings')
    op.drop_table('loyaltyprograms')
    op.drop_table('customers')
    op.drop_table('admins')
    # ### end Alembic commands ###
