"""Restaurant to User relationship

Revision ID: f7daec96602b
Revises: 8fbceecedf8e
Create Date: 2023-08-02 18:27:06.925612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7daec96602b'
down_revision = '8fbceecedf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_id_restaurants', 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_restaurants', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
