"""One to Many relationship MenuItem Order

Revision ID: fcc0efbb605c
Revises: 10f74bfeefb1
Create Date: 2023-08-07 11:56:23.450031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc0efbb605c'
down_revision = '10f74bfeefb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_id_orders', 'menuitems', ['item_id'], ['item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_id_orders', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
